# Generated by Django 4.0.4 on 2022-06-22 18:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_baby_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.upload_to),
        ),
    ]
