# Generated by Django 4.0.4 on 2022-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('img', models.ImageField(blank=True, max_length=255, upload_to='imgs/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
