# Generated by Django 4.0.4 on 2022-06-23 23:27

import baby.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0002_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=baby.models.upload_to),
        ),
    ]
